Repository adinhodovic/wagtail-resume, pull requests merged in 2023-10, with the labels that each got.

#76 feat: Allow hiding experiences
  poetry.lock
  pyproject.toml
  wagtail_resume/blocks.py
  wagtail_resume/migrations/0012_alter_baseresumepage_resume.py
  wagtail_resume/templates/wagtail_resume/blocks/work_experience_block.html
Labels: feat

#77 feat: Add option to only show x exp
  poetry.lock
  pyproject.toml
  tox.ini
  wagtail_resume/blocks.py
  wagtail_resume/migrations/0013_alter_baseresumepage_resume.py
  wagtail_resume/templates/wagtail_resume/blocks/work_experience_block.html
Labels: feat

#78 fix: Remove duplicate i18n loading
  wagtail_resume/templates/wagtail_resume/resume_page_body.html
Labels: fix

#79 ci: Add pull_request_target events for forks
  .github/workflows/ci-cd.yml
  .github/workflows/release-drafter.yml
Labels: ci

#80 chore: Bump version
  pyproject.toml
Labels: chore
